<?php

namespace AppBundle\Repository;

/**
 * CCTPSpecificRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CCTPSpecificRepository extends \Doctrine\ORM\EntityRepository
{
}
