<?php

namespace AppBundle\Repository;

/**
 * CCTPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CCTPRepository extends \Doctrine\ORM\EntityRepository
{
}
