<?php

namespace AppBundle\Repository;

/**
 * ContractantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractantRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll($type = 'acteur')
    {
        $qb = $this->createQueryBuilder('c')
                ->where('c.typeContractant = :typeContractant')
                ->setParameter('typeContractant', $type)
            ->getQuery();

        return $qb->getResult();
    }
}
