<?php

namespace AppBundle\Repository;

/**
 * DAGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DAGRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll()
    {
        $qb = $this->createQueryBuilder('dag')
            ->getQuery();

        return $qb->getResult();
    }

    public function findAll()
    {
        $qb = $this->createQueryBuilder('dag')
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function findDAGByIdProc($id_proc)
    {
        $qb = $this->createQueryBuilder('dag')
            ->join('dag.procs', 'proc')
            ->where('proc.id = :id')
            ->setParameter('id', $id_proc)
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function findById($id) {
        $qb = $this->createQueryBuilder('dag')
            ->where('dag.id = :id')
            ->setParameter('id', $id)
            ->getQuery();

        return $qb->getArrayResult();
    }
}
