<?php

namespace AppBundle\Repository;

/**
 * DAGRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DAGRepository extends \Doctrine\ORM\EntityRepository
{
}
