<?php

namespace AppBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll()
    {
        $qb = $this->createQueryBuilder('document')
            ->getQuery();

        return $qb->getResult();
    }

    public function findById($id_doc)
    {
        $qb = $this->createQueryBuilder('doc')
            ->where('doc.id = :id')
            ->setParameter('id', $id_doc)
            ->getQuery();

        return $qb->getResult();
    }

    public function findByProjet($id_projet)
    {
        $qb = $this->createQueryBuilder('doc')
            ->select([
                'doc.id',
                'dag.libelle',
                'doc.dateUpload',
                'doc.dateSignature',
                'doc.dateSave',
//                'fichierModifie.nom',
//                'fichierSigne.nom',
            ])
            ->join('doc.projet', 'projet')
            ->join('doc.dag', 'dag')
//            ->join('doc.fichierModifie', 'fichierModifie')
//            ->join('doc.fichierSigne', 'fichierSigne')
            ->where('projet.id = :id')
            ->setParameter('id', $id_projet)
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function findByProjet2($id_projet)
    {
        $qb = $this->createQueryBuilder('doc')
            ->join('doc.projet', 'projet')
            ->where('projet.id = :id')
            ->setParameter('id', $id_projet)
            ->getQuery();

        return $qb->getResult();
    }
}
