<?php

namespace AppBundle\Repository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll()
    {
        $qb = $this->createQueryBuilder('document')
            ->getQuery();

        return $qb->getResult();
    }

    public function findById($id_doc)
    {
        $qb = $this->createQueryBuilder('doc')
            ->where('doc.id = :id')
            ->setParameter('id', $id_doc)
            ->getQuery();

        return $qb->getResult();
    }
}
