<?php

namespace AppBundle\Repository;

/**
 * FichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FichierRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll()
    {
        $qb = $this->createQueryBuilder('v')
            ->getQuery();

        return $qb->getResult();
    }

    public function findByDag($id_dag)
    {
        $qb = $this->createQueryBuilder('f')
            ->join('f.dag', 'dag')
            ->where('dag.id = :id')
            ->setParameter('id', $id_dag)
            ->getQuery();

        return $qb->getResult();
    }
}
