<?php

namespace AppBundle\Repository;

/**
 * ProcRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcRepository extends \Doctrine\ORM\EntityRepository
{
    public function listAll()
    {
        $qb = $this->createQueryBuilder('p')
            ->getQuery();

        return $qb->getResult();
    }

    public function findProcByIdTP($id_tp)
    {
        $qb = $this->createQueryBuilder('proc')
            ->join('proc.tps', 'tp')
            ->where('tp.id = :id')
            ->setParameter('id', $id_tp)
            ->getQuery();

        return $qb->getArrayResult();
    }

    public function findAll()
    {
        $qb = $this->createQueryBuilder('v')
            ->getQuery();

        return $qb->getArrayResult();
    }
}
