<?php

namespace AppBundle\Repository;

/**
 * TDRRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TDRRepository extends \Doctrine\ORM\EntityRepository
{
}
