<?php

namespace AppBundle\Repository;

/**
 * TDRSpecificRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TDRSpecificRepository extends \Doctrine\ORM\EntityRepository
{
}
